#!/bin/bash
# 101-manage_my_process - Init script to manage manage_my_process

case "$1" in
    start)
        ./manage_my_process &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process started"
        ;;
    stop)
        if [ -e "/var/run/my_process.pid" ]; then
            pid=$(cat /var/run/my_process.pid)
            kill $pid
            rm /var/run/my_process.pid
            echo "manage_my_process stopped"
        else
            echo "No such file or directory: /var/run/my_process.pid"
        fi
        ;;
    restart)
        $0 stop
        $0 start
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0

