#!/usr/bin/env bash
# This script displays "Best School" 10 times and says "Hi" on the 9th iteration

# Counter variable
counter=0

# Using a while loop to display "Best School" 10 times
while [ $counter -lt 10 ]; do
    if [ $counter -eq 8 ]; then
        echo "Hi"
    else
        echo "Best School"
    fi
    ((counter++))
done
