#!/usr/bin/env bash
# displays Best School 10 times.

COUNTER=0
while [ $COUNTER -lt 10 ]
do
    if [ $COUNTER = 8 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    let ((COUNTER++))
done
