#!/usr/bin/env bash
# This script displays the time for 12 hrs and 59 mins

# Counter variables for hours and minutes
hour=0

# Using a while loop to iterate through hours
while [ $hour -lt 12 ]; do
    echo "Hour: $hour"

    # Counter variable for minutes
    minute=1

    # Using a nested while loop to iterate through minutes
    while [ $minute -lt 60 ]; do
        echo $minute
        ((minute++))
    done

    # Reset the minute counter
    minute=1

    ((hour++))
done
